import React from 'react';
import './Home.css'; // Import the CSS file

function Home() {
  return (
    <div>
      <h1>Home Page</h1>
      <p>Welcome to the Home dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage ddddde dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage dddddddddddddddddddPage!</p>
    </div>
  );
}

export default Home;
